name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: "Check ${{ matrix.test }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: [ 'unit-test', 'phpcs', 'psalm', 'phpstan' ]
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install dependencies
        run: composer install
      - name: Run tests
        run: composer run ${{ matrix.test }}